// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/database/repository_interface.go -destination=mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	database "crypto-rates/internal/database"
	types "crypto-rates/internal/types"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRateRepositoryInterface is a mock of RateRepositoryInterface interface.
type MockRateRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRateRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRateRepositoryInterfaceMockRecorder is the mock recorder for MockRateRepositoryInterface.
type MockRateRepositoryInterfaceMockRecorder struct {
	mock *MockRateRepositoryInterface
}

// NewMockRateRepositoryInterface creates a new mock instance.
func NewMockRateRepositoryInterface(ctrl *gomock.Controller) *MockRateRepositoryInterface {
	mock := &MockRateRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRateRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateRepositoryInterface) EXPECT() *MockRateRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetCurrentPrice mocks base method.
func (m *MockRateRepositoryInterface) GetCurrentPrice(ctx context.Context, currency types.Currency) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentPrice", ctx, currency)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentPrice indicates an expected call of GetCurrentPrice.
func (mr *MockRateRepositoryInterfaceMockRecorder) GetCurrentPrice(ctx, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentPrice", reflect.TypeOf((*MockRateRepositoryInterface)(nil).GetCurrentPrice), ctx, currency)
}

// GetHourlyChangePercent mocks base method.
func (m *MockRateRepositoryInterface) GetHourlyChangePercent(ctx context.Context, currency types.Currency) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHourlyChangePercent", ctx, currency)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHourlyChangePercent indicates an expected call of GetHourlyChangePercent.
func (mr *MockRateRepositoryInterfaceMockRecorder) GetHourlyChangePercent(ctx, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHourlyChangePercent", reflect.TypeOf((*MockRateRepositoryInterface)(nil).GetHourlyChangePercent), ctx, currency)
}

// GetRateInfo mocks base method.
func (m *MockRateRepositoryInterface) GetRateInfo(ctx context.Context, currency types.Currency) (*database.RateInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRateInfo", ctx, currency)
	ret0, _ := ret[0].(*database.RateInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRateInfo indicates an expected call of GetRateInfo.
func (mr *MockRateRepositoryInterfaceMockRecorder) GetRateInfo(ctx, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRateInfo", reflect.TypeOf((*MockRateRepositoryInterface)(nil).GetRateInfo), ctx, currency)
}

// GetSimpleDailyStats mocks base method.
func (m *MockRateRepositoryInterface) GetSimpleDailyStats(ctx context.Context, currency types.Currency) (float64, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimpleDailyStats", ctx, currency)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSimpleDailyStats indicates an expected call of GetSimpleDailyStats.
func (mr *MockRateRepositoryInterfaceMockRecorder) GetSimpleDailyStats(ctx, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimpleDailyStats", reflect.TypeOf((*MockRateRepositoryInterface)(nil).GetSimpleDailyStats), ctx, currency)
}

// SaveRate mocks base method.
func (m *MockRateRepositoryInterface) SaveRate(ctx context.Context, currency types.Currency, price float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRate", ctx, currency, price)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRate indicates an expected call of SaveRate.
func (mr *MockRateRepositoryInterfaceMockRecorder) SaveRate(ctx, currency, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRate", reflect.TypeOf((*MockRateRepositoryInterface)(nil).SaveRate), ctx, currency, price)
}
