// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/api/binance_client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/api/binance_client.go -destination=mocks/mock_binance.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	types "crypto-rates/internal/types"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBinanceClientInterface is a mock of BinanceClientInterface interface.
type MockBinanceClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBinanceClientInterfaceMockRecorder
	isgomock struct{}
}

// MockBinanceClientInterfaceMockRecorder is the mock recorder for MockBinanceClientInterface.
type MockBinanceClientInterfaceMockRecorder struct {
	mock *MockBinanceClientInterface
}

// NewMockBinanceClientInterface creates a new mock instance.
func NewMockBinanceClientInterface(ctrl *gomock.Controller) *MockBinanceClientInterface {
	mock := &MockBinanceClientInterface{ctrl: ctrl}
	mock.recorder = &MockBinanceClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinanceClientInterface) EXPECT() *MockBinanceClientInterfaceMockRecorder {
	return m.recorder
}

// GetRate mocks base method.
func (m *MockBinanceClientInterface) GetRate(ctx context.Context, currency types.Currency) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRate", ctx, currency)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRate indicates an expected call of GetRate.
func (mr *MockBinanceClientInterfaceMockRecorder) GetRate(ctx, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRate", reflect.TypeOf((*MockBinanceClientInterface)(nil).GetRate), ctx, currency)
}
