// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/rates": {
            "get": {
                "tags": [
                    "rates"
                ],
                "summary": "Получить все курсы",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.RatesResponse"
                        }
                    }
                }
            }
        },
        "/rates/{cryptocurrency}": {
            "get": {
                "tags": [
                    "rates"
                ],
                "summary": "Получить курс валюты",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BTC или ETH",
                        "name": "cryptocurrency",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.RateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rest.RateResponse": {
            "type": "object",
            "properties": {
                "change_1h": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "max_price_24h": {
                    "type": "number"
                },
                "min_price_24h": {
                    "type": "number"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "rest.RatesResponse": {
            "type": "object",
            "properties": {
                "rates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.RateResponse"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Crypto Rates API",
	Description:      "Сервис для отслеживания курсов криптовалют",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
